### ISSUE TITLE
Mark homework 1, exercise 1 & 2 of Sheng Guo

### ISSUE THREAD

**Issue by anyezijue49** [anyezijue49/stat679work#1] opened 2016-09-27 00:09 UTC
Dear @cecileane,

Here is my homework:
Exercise 1:
`https://github.com/anyezijue49/stat679work/commit/727e00f4149bff2f8510fd105389baf5aedf46f4`
Exercise 2:
`https://github.com/anyezijue49/stat679work/commit/7421773e3f5fbab9133f7590f4bfd21a06e025ad`
The first one is aimed to change filename of all **timetesty_snaq.log**
The second one will produce a cvs to record all information. Please make sure that your current directory include directories **log** and **out** .
Thank you.

Best Regards
Sheng

**Comment by cecileane** [comment] 2016-10-07 05:08
Hi Sheng,
Nice work! Your code worked just fine. Some feedback below.

You need a readme file in your directory `hw1`. It's part of getting into the habit of documenting your code and projects.

Your coding style is not very good: you have no indentation within the `do` and the `done` block in any of your loops. Indentation is crucial to make the code human-readable.

Unfortunately, you didn't get to use `grep` as much as intended, because you didn't use _extended_ regular expressions. It is great that you used parameter expansion (and also a clever use of `head -c` and `tail -c`), but parameter expansion is a lot less useful (generally) than `grep`, and learning to use extended regular expressions would be useful for all other languages, not just the shell. Later, it will also be much better to use `sed` instead of parameter expansion to do search/replace operations. `sed` can do a lot more than what you can do with parameter expansion, so it's best to learn to use (extended) regular expressions (using `grep` and then `sed`).

You could make you code more lean in several places, like this:

``` shell
echo -n ${filename%.*} >> result.csv
echo -n "," >> result.csv
```

could be done with simply `echo -n "${filename%.*}," >> result.csv`

or here you didn't need to write to a temporary file, move this temporary file and append its content to the result file:

``` shell
grep time "${filename%.*}".out | head -c 29 | tail -c 14 > temp2.txt
mv temp2.txt ../log/temp2.txt
cd ../log
echo -n "$(cat temp2.txt)" >> result.csv
echo >> result.csv
```

instead you could have directly appended what you wanted to the final result file directly:

``` shell
grep time "${filename%.*}".out | head -c 29 | tail -c 14 >> ../log/result.csv
```

(same thing for the first temporary file).

Please close this issue, or [assign](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) it to me and I can close it.

**Closed as completed** 2016-10-13 03:17 UTC
